In [1]:
import math
import pandas as pd
import numpy as np

In [8]:
hg38 = pd.read_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/bellenguez_hg38_parquet_flipped_a1a2.tsv', sep = '\t')

In [3]:
hg38

,CHR,BP,SNP,A1,A2,BETA,SE,P,N,MAF,OR,Z
0,1,594445,rs888953847,C,T,-0.0152,0.3236,0.9626,42140,0.0006,0.985000,-0.046972
1,1,595762,rs1040232850,CTG,C,0.2494,0.2247,0.2670,55422,0.0014,1.283697,1.109924
2,1,646157,rs1250812823,G,A,-0.3028,0.3180,0.3411,42140,0.0013,0.739000,-0.952201
3,1,730012,rs1362083662,G,T,-0.0319,0.4544,0.9441,42140,0.0009,0.969000,-0.070202
4,1,730804,rs1039158266,G,T,0.0540,0.2343,0.8176,55422,0.0013,1.055000,0.230474
...,...,...,...,...,...,...,...,...,...,...,...,...
16644753,22,50797709,rs534679861,C,T,0.0836,0.1253,0.5049,460939,0.0023,1.087000,0.667199
16644754,22,50797710,rs553688050,G,A,-0.0149,0.2003,0.9406,443137,0.0012,0.985000,-0.074388
16644755,22,50798635,rs3896457,T,C,0.0044,0.0103,0.6666,486567,0.2817,1.004016,0.427184
16644756,22,50799068,rs145825199,C,T,0.1502,0.2931,0.6083,429855,0.0009,1.162000,0.512453
16644757,22,50799107,rs782195205,A,C,0.0655,0.2898,0.8213,55422,0.0009,1.067236,0.226018

In [9]:
hg38 = hg38.rename(columns = {"BETA":'b', "SE":"se", "P":"p", "MAF":"freq"})

In [10]:
hg38[["SNP", "A1", "A2", "freq", "b", "se", "p", "N"]]

                   SNP   A1 A2    freq       b      se       p       N
0          rs888953847    C  T  0.0006 -0.0152  0.3236  0.9626   42140
1         rs1040232850  CTG  C  0.0014  0.2494  0.2247  0.2670   55422
2         rs1250812823    G  A  0.0013 -0.3028  0.3180  0.3411   42140
3         rs1362083662    G  T  0.0009 -0.0319  0.4544  0.9441   42140
4         rs1039158266    G  T  0.0013  0.0540  0.2343  0.8176   55422
...                ...  ... ..     ...     ...     ...     ...     ...
16644753   rs534679861    C  T  0.0023  0.0836  0.1253  0.5049  460939
16644754   rs553688050    G  A  0.0012 -0.0149  0.2003  0.9406  443137
16644755     rs3896457    T  C  0.2817  0.0044  0.0103  0.6666  486567
16644756   rs145825199    C  T  0.0009  0.1502  0.2931  0.6083  429855
16644757   rs782195205    A  C  0.0009  0.0655  0.2898  0.8213   55422

[16644758 rows x 8 columns]

In [11]:
#hg38[["SNP","A1", "A2", "freq", "b", "se", "p", "N"]].to_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_from_parquet_reversed_a1a2.cojo',sep = '\t', index = False)

hg38[["SNP","A1", "A2", "freq", "b", "se", "p", "N"]].to_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_from_parquet_reversed_a1a2.cojo',sep = '\t', index = False)

In [12]:
for chr_num in range(1, 23):
    chr_data = hg38[hg38.CHR == chr_num].loc[:, ["SNP", "A1", "A2", "freq", "b", "se", "p", "N"]]
    output_file = f'/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr{chr_num}_from_parquet_reversed.cojo'
    chr_data.to_csv(output_file, sep='\t', index=False)
    print(f"Chromosome {chr_num} data saved to {output_file}")

Chromosome 1 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr1_from_parquet_reversed.cojo
Chromosome 2 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr2_from_parquet_reversed.cojo
Chromosome 3 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr3_from_parquet_reversed.cojo
Chromosome 4 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr4_from_parquet_reversed.cojo
Chromosome 5 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr5_from_parquet_reversed.cojo
Chromosome 6 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr6_from_parquet_reversed.cojo
Chromosome 7 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr7_from_parquet_reversed.cojo
Chromosome 8 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr8_from_parquet_reversed.cojo
Chromosome 9 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr9_from_parquet_reversed.cojo
Chromosome 10 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr10_from_parquet_reversed.cojo
Chromosome 11 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr11_from_parquet_reversed.cojo
Chromosome 12 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr12_from_parquet_reversed.cojo
Chromosome 13 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr13_from_parquet_reversed.cojo
Chromosome 14 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr14_from_parquet_reversed.cojo
Chromosome 15 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr15_from_parquet_reversed.cojo
Chromosome 16 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr16_from_parquet_reversed.cojo
Chromosome 17 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr17_from_parquet_reversed.cojo
Chromosome 18 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr18_from_parquet_reversed.cojo
Chromosome 19 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr19_from_parquet_reversed.cojo
Chromosome 20 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr20_from_parquet_reversed.cojo
Chromosome 21 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr21_from_parquet_reversed.cojo
Chromosome 22 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/rerun/bellenguez_hg38_chr22_from_parquet_reversed.cojo

### previous doesnt work

In [6]:
hg38 = pd.read_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/bellenguez_hg38_from_parquet.tsv', sep = '\t')

In [7]:
## check what column we need
## cojo needs SNP A1 A2 freq b se p N 
hg38

          CHR        BP           SNP A2 A1         Z       N       MAF
0           1    594445   rs888953847  C  T -0.046891   42140  0.000355
1           1    646157  rs1250812823  G  A -0.951994   42140  0.001682
2           1    730012  rs1362083662  G  T -0.070118   42140  0.002223
3           1    730804  rs1039158266  G  T  0.230633   55422  0.000439
4           1    730869   rs200188737  C  T  0.374275  429855  0.001672
...       ...       ...           ... .. ..       ...     ...       ...
15954868   22  50796846  rs1173631322  A  G -0.868355   42140  0.000711
15954869   22  50796989  rs1185943124  T  G  1.283834   52323  0.000490
15954870   22  50797531   rs200189535  T  C  0.906635  477993  0.156239
15954871   22  50798635     rs3896457  T  C  0.430819  486567  0.299703
15954872   22  50799107   rs782195205  A  C  0.225873   55422  0.000270

[15954873 rows x 8 columns]

In [4]:
hg38['se'] = 1/np.sqrt(2*hg38.N*hg38.MAF*(1-hg38.MAF))
hg38['b'] = hg38.Z * hg38.se
from scipy.stats import norm
hg38['p'] = 2 * (1 - norm.cdf(np.abs(hg38.Z)))

In [6]:
hg38.to_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/bellenguez_hg38_from_parquet_allinfo.tsv', sep = '\t', index = False)

### double checked, A1, A2 is defined opposited. So we need to reverse it.

In [2]:
hg38 = pd.read_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/bellenguez_hg38_from_parquet_allinfo.tsv',sep = '\t')
hg38

,CHR,BP,SNP,A2,A1,Z,N,MAF,se,b,p
0,1,594445,rs888953847,C,T,-0.046891,42140,0.000355,0.182758,-0.008570,0.9626
1,1,646157,rs1250812823,G,A,-0.951994,42140,0.001682,0.084071,-0.080035,0.3411
2,1,730012,rs1362083662,G,T,-0.070118,42140,0.002223,0.073139,-0.005128,0.9441
3,1,730804,rs1039158266,G,T,0.230633,55422,0.000439,0.143448,0.033084,0.8176
4,1,730869,rs200188737,C,T,0.374275,429855,0.001672,0.026395,0.009879,0.7082
...,...,...,...,...,...,...,...,...,...,...,...
15954868,22,50796846,rs1173631322,A,G,-0.868355,42140,0.000711,0.129237,-0.112224,0.3852
15954869,22,50796989,rs1185943124,T,G,1.283834,52323,0.000490,0.139729,0.179389,0.1992
15954870,22,50797531,rs200189535,T,C,0.906635,477993,0.156239,0.002817,0.002554,0.3646
15954871,22,50798635,rs3896457,T,C,0.430819,486567,0.299703,0.002213,0.000953,0.6666
15954872,22,50799107,rs782195205,A,C,0.225873,55422,0.000270,0.182864,0.041304,0.8213

In [3]:
hg38 = hg38.rename(columns = {"MAF":'freq', "A2":"A1", "A1":"A2"})
hg38

,CHR,BP,SNP,A1,A2,Z,N,freq,se,b,p
0,1,594445,rs888953847,C,T,-0.046891,42140,0.000355,0.182758,-0.008570,0.9626
1,1,646157,rs1250812823,G,A,-0.951994,42140,0.001682,0.084071,-0.080035,0.3411
2,1,730012,rs1362083662,G,T,-0.070118,42140,0.002223,0.073139,-0.005128,0.9441
3,1,730804,rs1039158266,G,T,0.230633,55422,0.000439,0.143448,0.033084,0.8176
4,1,730869,rs200188737,C,T,0.374275,429855,0.001672,0.026395,0.009879,0.7082
...,...,...,...,...,...,...,...,...,...,...,...
15954868,22,50796846,rs1173631322,A,G,-0.868355,42140,0.000711,0.129237,-0.112224,0.3852
15954869,22,50796989,rs1185943124,T,G,1.283834,52323,0.000490,0.139729,0.179389,0.1992
15954870,22,50797531,rs200189535,T,C,0.906635,477993,0.156239,0.002817,0.002554,0.3646
15954871,22,50798635,rs3896457,T,C,0.430819,486567,0.299703,0.002213,0.000953,0.6666
15954872,22,50799107,rs782195205,A,C,0.225873,55422,0.000270,0.182864,0.041304,0.8213

In [4]:
## reverse other stuff too!
hg38.b = -hg38.b
hg38.freq = 1- hg38.freq
hg38.se =  1/np.sqrt(2*hg38.N*hg38.freq*(1-hg38.freq))

In [5]:
hg38

,CHR,BP,SNP,A1,A2,Z,N,freq,se,b,p
0,1,594445,rs888953847,C,T,-0.046891,42140,0.999645,0.182758,0.008570,0.9626
1,1,646157,rs1250812823,G,A,-0.951994,42140,0.998318,0.084071,0.080035,0.3411
2,1,730012,rs1362083662,G,T,-0.070118,42140,0.997777,0.073139,0.005128,0.9441
3,1,730804,rs1039158266,G,T,0.230633,55422,0.999561,0.143448,-0.033084,0.8176
4,1,730869,rs200188737,C,T,0.374275,429855,0.998328,0.026395,-0.009879,0.7082
...,...,...,...,...,...,...,...,...,...,...,...
15954868,22,50796846,rs1173631322,A,G,-0.868355,42140,0.999289,0.129237,0.112224,0.3852
15954869,22,50796989,rs1185943124,T,G,1.283834,52323,0.999510,0.139729,-0.179389,0.1992
15954870,22,50797531,rs200189535,T,C,0.906635,477993,0.843761,0.002817,-0.002554,0.3646
15954871,22,50798635,rs3896457,T,C,0.430819,486567,0.700297,0.002213,-0.000953,0.6666
15954872,22,50799107,rs782195205,A,C,0.225873,55422,0.999730,0.182864,-0.041304,0.8213

In [7]:
##SNP A1 A2 freq b se p N 
save = hg38.loc[:,["SNP", "A1", "A2", "freq", "b" ,"se" ,"p" ,"N"]]
save

                   SNP A1 A2      freq         b        se       p       N
0          rs888953847  C  T  0.999645  0.008570  0.182758  0.9626   42140
1         rs1250812823  G  A  0.998318  0.080035  0.084071  0.3411   42140
2         rs1362083662  G  T  0.997777  0.005128  0.073139  0.9441   42140
3         rs1039158266  G  T  0.999561 -0.033084  0.143448  0.8176   55422
4          rs200188737  C  T  0.998328 -0.009879  0.026395  0.7082  429855
...                ... .. ..       ...       ...       ...     ...     ...
15954868  rs1173631322  A  G  0.999289  0.112224  0.129237  0.3852   42140
15954869  rs1185943124  T  G  0.999510 -0.179389  0.139729  0.1992   52323
15954870   rs200189535  T  C  0.843761 -0.002554  0.002817  0.3646  477993
15954871     rs3896457  T  C  0.700297 -0.000953  0.002213  0.6666  486567
15954872   rs782195205  A  C  0.999730 -0.041304  0.182864  0.8213   55422

[15954873 rows x 8 columns]

In [8]:
save.to_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_from_parquet_reversed.cojo', sep = '\t', index = False)

In [9]:
#hg38[hg38.CHR==21].loc[:,["SNP", "A1", "A2", "freq", "b" ,"se" ,"p" ,"N"]].to_csv('/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr21_from_parquet.cojo', sep = '\t', index = False)

for chr_num in range(1, 23):
    # Filter for the current chromosome
    chr_data = hg38[hg38.CHR == chr_num].loc[:, ["SNP", "A1", "A2", "freq", "b", "se", "p", "N"]]
    output_file = f'/gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr{chr_num}_from_parquet_reversed.cojo'
    
    chr_data.to_csv(output_file, sep='\t', index=False)

    print(f"Chromosome {chr_num} data saved to {output_file}")

Chromosome 1 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr1_from_parquet_reversed.cojo
Chromosome 2 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr2_from_parquet_reversed.cojo
Chromosome 3 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr3_from_parquet_reversed.cojo
Chromosome 4 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr4_from_parquet_reversed.cojo
Chromosome 5 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr5_from_parquet_reversed.cojo
Chromosome 6 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr6_from_parquet_reversed.cojo
Chromosome 7 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr7_from_parquet_reversed.cojo
Chromosome 8 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr8_from_parquet_reversed.cojo
Chromosome 9 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr9_from_parquet_reversed.cojo
Chromosome 10 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr10_from_parquet_reversed.cojo
Chromosome 11 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr11_from_parquet_reversed.cojo
Chromosome 12 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr12_from_parquet_reversed.cojo
Chromosome 13 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr13_from_parquet_reversed.cojo
Chromosome 14 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr14_from_parquet_reversed.cojo
Chromosome 15 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr15_from_parquet_reversed.cojo
Chromosome 16 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr16_from_parquet_reversed.cojo
Chromosome 17 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr17_from_parquet_reversed.cojo
Chromosome 18 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr18_from_parquet_reversed.cojo
Chromosome 19 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr19_from_parquet_reversed.cojo
Chromosome 20 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr20_from_parquet_reversed.cojo
Chromosome 21 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr21_from_parquet_reversed.cojo
Chromosome 22 data saved to /gpfs/commons/groups/knowles_lab/data/ADSP_reguloML/summary_stats/alzheimers/fixed_alzheimers/processed/sbayesrc/bellenguez_hg38_chr22_from_parquet_reversed.cojo